#!/usr/bin/env python

import sys
import images2gif
try:
    import argparse
except ImportError:
    print "You must have argparse installed"
    sys.exit(1)
try:
    from PIL import Image
except ImportError:
    print "You must have PIL installed"
    sys.exit(1)

parser = argparse.ArgumentParser(description='Turn images into an animated gif.')
parser.add_argument('files', type=argparse.FileType('r'), nargs='+', metavar='F', help='image file to use in gif')
parser.add_argument('outfile', type=argparse.FileType('w'), nargs=1, metavar='OF', help='file to write out to')

try:
    args = parser.parse_args()
except IOError, e:
    print 'pygifme had the following error:'
    print e
    sys.exit(2)

images = [Image.open(imagearg.name) for imagearg in args.files]
outfile = args.outfile[0].name
args.outfile[0].close()

try:
    images2gif.writeGif(outfile, images)
except IOError, e:
    print 'pygifme had the following error:'
    print e
    sys.exit(2)
